---@meta

---Non-legacy validation spec (>=v0.11)
---@class ValidateSpec
---@field [1] any
---@field [2] vim.validate.Validator
---@field [3]? boolean
---@field [4]? string

---@alias DirectionFunc fun(t: table<string, any>): new_direction: table<string, any>

---@class DirectionFuncs
---@field r DirectionFunc
---@field l DirectionFunc

---@class WhichColorschemeGroup
---@field [1]? string
---@field [2]? string
---@field [3]? string
---@field [4]? string
---@field [5]? string
---@field [6]? string
---@field [7]? string
---@field [8]? string
---@field [9]? string

---@alias WhichColorschemeGroups table <string, WhichColorschemeGroup>

---@class WhichColorschemeGroupping
---@field uppercase_groups? boolean
---@field random? boolean
---@field inverse? boolean
---@field current_first? boolean

---@class WhichColorschemeOpts
---@field prefix? string
---@field group_name? string
---@field include_builtin? boolean
---@field grouping? WhichColorschemeGroupping
---@field custom_groups? WhichColorschemeGroups

---@alias Letter
---|'a'
---|'b'
---|'c'
---|'d'
---|'e'
---|'f'
---|'g'
---|'h'
---|'i'
---|'j'
---|'k'
---|'l'
---|'m'
---|'n'
---|'o'
---|'p'
---|'q'
---|'r'
---|'s'
---|'t'
---|'u'
---|'v'
---|'w'
---|'x'
---|'y'
---|'z'
---|'A'
---|'B'
---|'C'
---|'D'
---|'E'
---|'F'
---|'G'
---|'H'
---|'I'
---|'J'
---|'K'
---|'L'
---|'M'
---|'N'
---|'O'
---|'P'
---|'Q'
---|'R'
---|'S'
---|'T'
---|'U'
---|'V'
---|'W'
---|'X'
---|'Y'
---|'Z'

-- vim: set ts=2 sts=2 sw=2 et ai si sta:
