---@meta

---Non-legacy validation spec (>=v0.11)
---@class (exact) WhichColorscheme.ValidateSpec
---@field [1] any
---@field [2] vim.validate.Validator
---@field [3]? boolean
---@field [4]? string

---@class (exact) WhichColorschemeGroup
---@field [1]? string
---@field [2]? string
---@field [3]? string
---@field [4]? string
---@field [5]? string
---@field [6]? string
---@field [7]? string
---@field [8]? string
---@field [9]? string

---@class (exact) WhichColorschemeOpts.Labels
---@field A? string
---@field B? string
---@field C? string
---@field D? string
---@field E? string
---@field F? string
---@field G? string
---@field H? string
---@field I? string
---@field J? string
---@field K? string
---@field L? string
---@field M? string
---@field N? string
---@field O? string
---@field P? string
---@field Q? string
---@field R? string
---@field S? string
---@field T? string
---@field U? string
---@field V? string
---@field W? string
---@field Y? string
---@field Z? string
---@field ["'"]? string
---@field ['!']? string
---@field ['"']? string
---@field ['#']? string
---@field ['$']? string
---@field ['%']? string
---@field ['&']? string
---@field ['(']? string
---@field [')']? string
---@field ['*']? string
---@field ['+']? string
---@field [',']? string
---@field ['-']? string
---@field ['.']? string
---@field ['/']? string
---@field ['0']? string
---@field ['1']? string
---@field ['2']? string
---@field ['3']? string
---@field ['4']? string
---@field ['5']? string
---@field ['6']? string
---@field ['7']? string
---@field ['8']? string
---@field ['9']? string
---@field [':']? string
---@field [';']? string
---@field ['<']? string
---@field ['=']? string
---@field ['>']? string
---@field ['?']? string
---@field ['@']? string
---@field ['[']? string
---@field ['\\']? string
---@field [']']? string
---@field ['^']? string
---@field ['_']? string
---@field ['`']? string
---@field ['{']? string
---@field ['|']? string
---@field ['}']? string
---@field ['~']? string
---@field a? string
---@field b? string
---@field c? string
---@field d? string
---@field e? string
---@field f? string
---@field g? string
---@field h? string
---@field i? string
---@field j? string
---@field k? string
---@field l? string
---@field m? string
---@field n? string
---@field o? string
---@field p? string
---@field q? string
---@field r? string
---@field s? string
---@field t? string
---@field u? string
---@field v? string
---@field w? string
---@field y? string
---@field z? string

---@class (exact) WhichColorschemeOpts.Groups
---@field A? WhichColorschemeGroup
---@field B? WhichColorschemeGroup
---@field C? WhichColorschemeGroup
---@field D? WhichColorschemeGroup
---@field E? WhichColorschemeGroup
---@field F? WhichColorschemeGroup
---@field G? WhichColorschemeGroup
---@field H? WhichColorschemeGroup
---@field I? WhichColorschemeGroup
---@field J? WhichColorschemeGroup
---@field K? WhichColorschemeGroup
---@field L? WhichColorschemeGroup
---@field M? WhichColorschemeGroup
---@field N? WhichColorschemeGroup
---@field O? WhichColorschemeGroup
---@field P? WhichColorschemeGroup
---@field Q? WhichColorschemeGroup
---@field R? WhichColorschemeGroup
---@field S? WhichColorschemeGroup
---@field T? WhichColorschemeGroup
---@field U? WhichColorschemeGroup
---@field V? WhichColorschemeGroup
---@field W? WhichColorschemeGroup
---@field X? WhichColorschemeGroup
---@field Y? WhichColorschemeGroup
---@field Z? WhichColorschemeGroup
---@field a? WhichColorschemeGroup
---@field b? WhichColorschemeGroup
---@field c? WhichColorschemeGroup
---@field d? WhichColorschemeGroup
---@field e? WhichColorschemeGroup
---@field f? WhichColorschemeGroup
---@field g? WhichColorschemeGroup
---@field h? WhichColorschemeGroup
---@field i? WhichColorschemeGroup
---@field j? WhichColorschemeGroup
---@field k? WhichColorschemeGroup
---@field l? WhichColorschemeGroup
---@field m? WhichColorschemeGroup
---@field n? WhichColorschemeGroup
---@field o? WhichColorschemeGroup
---@field p? WhichColorschemeGroup
---@field q? WhichColorschemeGroup
---@field r? WhichColorschemeGroup
---@field s? WhichColorschemeGroup
---@field t? WhichColorschemeGroup
---@field u? WhichColorschemeGroup
---@field v? WhichColorschemeGroup
---@field w? WhichColorschemeGroup
---@field x? WhichColorschemeGroup
---@field y? WhichColorschemeGroup
---@field z? WhichColorschemeGroup

---@class (exact) WhichColorschemeOpts.Grouping
---@field current_first? boolean
---@field inverse? boolean
---@field labels? WhichColorschemeOpts.Labels
---@field random? boolean
---@field uppercase_groups? boolean

---@class (exact) WhichColorschemeDefaults.Grouping: WhichColorschemeOpts.Grouping
---@field current_first boolean
---@field inverse boolean
---@field labels WhichColorschemeOpts.Labels
---@field random boolean
---@field uppercase_groups boolean

---@class (exact) WhichColorschemeOpts
---@field custom_groups? WhichColorschemeOpts.Groups
---@field custom_only? boolean
---@field description_prefix? string
---@field enabled? boolean
---@field excluded? string[]
---@field group_name? string
---@field grouping? WhichColorschemeOpts.Grouping
---@field include_builtin? boolean
---@field prefix? string

---@class (exact) WhichColorschemeDefaults: WhichColorschemeOpts
---@field custom_groups WhichColorschemeOpts.Groups
---@field custom_only boolean
---@field description_prefix string
---@field enabled boolean
---@field excluded string[]
---@field group_name string
---@field grouping WhichColorschemeOpts.Grouping
---@field include_builtin boolean
---@field prefix string

---@alias Letter
---|'a'
---|'b'
---|'c'
---|'d'
---|'e'
---|'f'
---|'g'
---|'h'
---|'i'
---|'j'
---|'k'
---|'l'
---|'m'
---|'n'
---|'o'
---|'p'
---|'q'
---|'r'
---|'s'
---|'t'
---|'u'
---|'v'
---|'w'
---|'x'
---|'y'
---|'z'
---|'A'
---|'B'
---|'C'
---|'D'
---|'E'
---|'F'
---|'G'
---|'H'
---|'I'
---|'J'
---|'K'
---|'L'
---|'M'
---|'N'
---|'O'
---|'P'
---|'Q'
---|'R'
---|'S'
---|'T'
---|'U'
---|'V'
---|'W'
---|'X'
---|'Y'
---|'Z'

-- vim: set ts=2 sts=2 sw=2 et ai si sta:
