---@meta
---@diagnostic disable:unused-local

---Non-legacy validation spec (>=v0.11)
---@class WhichColorscheme.ValidateSpec
---@field [1] any
---@field [2] vim.validate.Validator
---@field [3]? boolean
---@field [4]? string

---@alias DirectionFunc fun(t: table<string, any>): new_direction: table<string, any>

---@class DirectionFuncs
local D = {}

---@param t table<string, any>
---@return table<string, any>
---@nodiscard
function D.l(t) end

---@param t table<string, any>
---@return table<string, any>
---@nodiscard
function D.r(t) end

---@class WhichColorschemeGroup
---@field [1]? string
---@field [2]? string
---@field [3]? string
---@field [4]? string
---@field [5]? string
---@field [6]? string
---@field [7]? string
---@field [8]? string
---@field [9]? string

---@alias WhichColorschemeGroups table <string, WhichColorschemeGroup>

---@class WhichColorschemeGrouping.Labels
---@field A? string
---@field B? string
---@field C? string
---@field D? string
---@field E? string
---@field F? string
---@field G? string
---@field H? string
---@field I? string
---@field J? string
---@field K? string
---@field L? string
---@field M? string
---@field N? string
---@field O? string
---@field P? string
---@field Q? string
---@field R? string
---@field S? string
---@field T? string
---@field U? string
---@field V? string
---@field W? string
---@field X? string
---@field Y? string
---@field Z? string
---@field a? string
---@field b? string
---@field c? string
---@field d? string
---@field e? string
---@field f? string
---@field g? string
---@field h? string
---@field i? string
---@field j? string
---@field k? string
---@field l? string
---@field m? string
---@field n? string
---@field o? string
---@field p? string
---@field q? string
---@field r? string
---@field s? string
---@field t? string
---@field u? string
---@field v? string
---@field w? string
---@field x? string
---@field y? string
---@field z? string

---@class WhichColorschemeGrouping
---@field uppercase_groups? boolean
---@field random? boolean
---@field inverse? boolean
---@field current_first? boolean
---@field labels? WhichColorschemeGrouping.Labels|table<Letter, string>

---@class WhichColorschemeOpts
---@field enabled? boolean
---@field custom_groups? WhichColorschemeGroups
---@field custom_only? boolean
---@field description_prefix? string
---@field excluded? string[]
---@field group_name? string
---@field grouping? WhichColorschemeGrouping
---@field include_builtin? boolean
---@field prefix? string

---@alias Letter
---|'a'
---|'b'
---|'c'
---|'d'
---|'e'
---|'f'
---|'g'
---|'h'
---|'i'
---|'j'
---|'k'
---|'l'
---|'m'
---|'n'
---|'o'
---|'p'
---|'q'
---|'r'
---|'s'
---|'t'
---|'u'
---|'v'
---|'w'
---|'x'
---|'y'
---|'z'
---|'A'
---|'B'
---|'C'
---|'D'
---|'E'
---|'F'
---|'G'
---|'H'
---|'I'
---|'J'
---|'K'
---|'L'
---|'M'
---|'N'
---|'O'
---|'P'
---|'Q'
---|'R'
---|'S'
---|'T'
---|'U'
---|'V'
---|'W'
---|'X'
---|'Y'
---|'Z'

-- vim: set ts=2 sts=2 sw=2 et ai si sta:
